### PR TITLE
Add ASPLOS 2022 paper AStitch.

### PR DESCRIPTION
**Pull request by JamesTheZ**

### CODE REVIEW

**Comment by merrymercy** [comment]
Thanks for the great work. It is glad to see this work is finally accepted by a top-tier conference.
Because this work builds on top of XLA, it introduces new optimizations instead of a new compiler architecture or a new IR.
This paper is better to be placed under `### CPU and GPU Optimization`

**Comment by JamesTheZ** [comment]
> Thanks for the great work. It is glad to see this work is finally accepted by a top-tier conference. Because this work builds on top of XLA, it introduces new optimizations instead of a new compiler architecture or a new IR. This paper is better to be placed under `### CPU and GPU Optimization`

Thanks for you suggestion. Actually, the insight of the currently version is a new optimizing compiler for memory intensive computations. The current version studies about one of the most important topic of a compiler, which is automatic code generation technique. It provides a new set of automatic code generation technique to generate the schedule of memory intensive op sub-graph. It is not a work about GPU optimization based on some other compiling processes. It actually re-implements the whole fusion and code generation functions of XLA, because the fusion and codegen approach are totally different between XLA and AStitch. None of existing compiler can generate the schedule like that in AStitch. We believe AStitch widens the codegen optimization space as a new optimizing compiler.
Anyway, I just hope it could be put in the right place to avoid the reader's preconceived misconceptions.

**Comment by merrymercy** [comment]
I see. Now I understand the significance of your work better. On the other hand, the current classification in this repo is confusing. I will accept your PR, but I may do some reorganization and change the title of some sections later.

**Comment by JamesTheZ** [comment]
> I see. Now I understand the significance of your work better. On the other hand, the current classification in this repo is confusing. I will accept your PR, but I may do some reorganization and change the title of some sections later.

Sure. I believe you will organize this document better. All practitioners in this field should thank you for this repo!

**Pull request merged**
